site_name: "FairML Datasets"
theme:
  name: "material"
  palette:
    primary: "green"
    accent: "green"
  features:
    - content.code.copy
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share

markdown_extensions:
  - mkdocs-click
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_category_heading: true
            heading_level: 2

nav:
  - Home: index.md
  - Getting Started: guide/getting-started.md
  - Datasets Overview (external): https://ashy-smoke-02965b70f.6.azurestaticapps.net/
  - API Reference:
      - Dataset: api/dataset.md
      - Datasets: api/datasets.md
      - Scenario: api/scenario.md
      - Collection: api/collection.md
      - Collections: api/collections.md
      - Transformations: api/transform.md
  - CLI Reference: cli.md
